//Para requisições com body:
//Content-Type: application/json
//Pule 1 linha
// {}

//Para requisições com headers:
//Authorization: "token"


### //endpoint teste
GET http://localhost:3003/teste

###
POST http://localhost:3003/user
Content-Type: application/json

{
	"name": "Monkey D. Luffy",
	"nickname": "Mugiwara",
	"email": "mugiwara-no-luffy@onepiece.com.br"
}

### 
GET http://localhost:3003/user/all

### 
GET http://localhost:3003/user/c5ee1863-f4ca-41a3-836f-f45bcdf9219c

### 
GET http://localhost:3003/user/edit/c5ee1863-f4ca-41a3-836f-f45bcdf9219c